#include "vk_settings.h"
#include <QSettings>
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QTextStream>
#include <QStringConverter>

QString VkSettings::configFilePath()
{
    const QString dir = QCoreApplication::applicationDirPath();
    return dir + QDir::separator() + "virtual_keyboard_config.ini";
}

VkSettings& VkSettings::instance()
{
    static VkSettings instance;
    return instance;
}

VkSettings::VkSettings()
{
    load();
}

void VkSettings::load()
{
    const QString path = configFilePath();
    QSettings settings(path, QSettings::IniFormat);

    m_language             = settings.value("General/language").toString();
    m_midiOutputPortName  = settings.value("MIDI/outputPortName").toString();
    m_midiInputPortName   = settings.value("MIDI/inputPortName").toString();
    m_soundFontPath       = settings.value("MIDI/soundFontPath").toString();

    const QString deviceIdHex = settings.value("Audio/outputDeviceId").toString();
    m_audioOutputDeviceId = QByteArray::fromHex(deviceIdHex.toLatin1());
    m_synthGain = settings.value("Audio/synthGain", 0.8).toFloat();
}

void VkSettings::save()
{
    const QString path = configFilePath();
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return;

    QTextStream out(&file);
    out.setEncoding(QStringConverter::Utf8);

    out << "; Virtual MIDI Keyboard Configuration\n";
    out << "; This file is automatically generated. Edit with care.\n\n";

    out << "[General]\n";
    out << "; Language (empty = system default)\n";
    out << "language=" << m_language << "\n\n";

    out << "[MIDI]\n";
    out << "; MIDI output port name (empty = built-in software synthesizer)\n";
    out << "outputPortName=" << m_midiOutputPortName << "\n";
    out << "; MIDI input port name (empty = none / no external controller)\n";
    out << "inputPortName=" << m_midiInputPortName << "\n";
    out << "; Path to SoundFont (.sf2) for software synthesizer\n";
    out << "soundFontPath=" << m_soundFontPath << "\n\n";

    out << "[Audio]\n";
    out << "; Audio output device ID (hex encoded)\n";
    out << "outputDeviceId=" << QString::fromLatin1(m_audioOutputDeviceId.toHex()) << "\n";
    out << "; FluidSynth master gain (0.1 to 2.0, default 0.8)\n";
    out << "synthGain=" << m_synthGain << "\n";

    file.close();
}
