#include "vk_settings.h"
#include <QSettings>
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QTextStream>
#include <QStringConverter>

QString VkSettings::configFilePath() {
    const QString dir = QCoreApplication::applicationDirPath();
    return dir + QDir::separator() + "virtual_keyboard_config.ini";
}

VkSettings& VkSettings::instance() {
    static VkSettings instance;
    return instance;
}

VkSettings::VkSettings() {
    load();
}

void VkSettings::load() {
    const QString path = configFilePath();
    QSettings settings(path, QSettings::IniFormat);

    m_midiOutputIndex = settings.value("MIDI/outputDeviceIndex", 0).toInt();  // 0 = built-in
    m_midiInputIndex = settings.value("MIDI/inputDeviceIndex", -1).toInt();
    m_soundFontPath = settings.value("MIDI/soundFontPath").toString();
    m_audioOutputIndex = settings.value("Audio/outputDeviceIndex", 0).toInt();
    const QString deviceIdHex = settings.value("Audio/outputDeviceId").toString();
    m_audioOutputDeviceId = QByteArray::fromHex(deviceIdHex.toLatin1());
}

void VkSettings::save() {
    const QString path = configFilePath();
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return;

    QTextStream out(&file);
    out.setEncoding(QStringConverter::Utf8);

    out << "; Virtual MIDI Keyboard Configuration\n";
    out << "; This file is automatically generated. Edit with care.\n\n";

    out << "[MIDI]\n";
    out << "; MIDI output device index (0-based, -1 for built-in synth)\n";
    out << "outputDeviceIndex=" << m_midiOutputIndex << "\n";
    out << "; MIDI input device index (to forward MIDI to output, -1 for none)\n";
    out << "inputDeviceIndex=" << m_midiInputIndex << "\n";
    out << "; Path to SoundFont (.sf2) for software synthesizer\n";
    out << "soundFontPath=" << m_soundFontPath << "\n\n";

    out << "[Audio]\n";
    out << "; Audio output device index for software synth\n";
    out << "outputDeviceIndex=" << m_audioOutputIndex << "\n";
    out << "; Audio output device ID (hex encoded)\n";
    out << "outputDeviceId=" << QString::fromLatin1(m_audioOutputDeviceId.toHex()) << "\n";

    file.close();
}
