#include "appsettings.h"
#include <QSettings>
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QTextStream>
#include <QStringConverter>

static QString configFilePath()
{
    QString dir = QCoreApplication::applicationDirPath();
    return dir + QDir::separator() + "config.ini";
}

AppSettings& AppSettings::instance()
{
    static AppSettings instance;
    return instance;
}

AppSettings::AppSettings()
{
    load();
}

void AppSettings::load()
{
    const QString path = configFilePath();
    QSettings settings(path, QSettings::IniFormat);

    settings.beginGroup("");
    m_theme = settings.value("theme", "dark").toString();
    m_language = settings.value("language").toString();
    settings.endGroup();
    m_midiDeviceIndex = settings.value("MIDI/deviceIndex", 0).toInt();
    m_soundFontPath = settings.value("MIDI/soundFontPath").toString();
    m_audioInputDeviceIndex = settings.value("Audio/inputDeviceIndex", 0).toInt();
    QString deviceIdHex = settings.value("Audio/inputDeviceId").toString();
    m_audioInputDeviceId = QByteArray::fromHex(deviceIdHex.toLatin1());
    QString outputDeviceIdHex = settings.value("Audio/outputDeviceId").toString();
    m_audioOutputDeviceId = QByteArray::fromHex(outputDeviceIdHex.toLatin1());
    m_projectLocation = settings.value("Project/location").toString();
}

void AppSettings::save()
{
    const QString path = configFilePath();
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return;

    QTextStream out(&file);
    out.setEncoding(QStringConverter::Utf8);

    out << "; Musician's Canvas Configuration\n";
    out << "; This file is automatically generated. Edit with care.\n\n";

    out << "[General]\n";
    out << "; GUI theme: dark or light\n";
    out << "theme=" << m_theme << "\n";
    out << "; Language (empty = system default)\n";
    out << "language=" << m_language << "\n\n";

    out << "[MIDI]\n";
    out << "; Default MIDI input device index (-1 for no device)\n";
    out << "deviceIndex=" << m_midiDeviceIndex << "\n";
    out << "; Path to SoundFont (.sf2) file for MIDI synthesis\n";
    out << "soundFontPath=" << m_soundFontPath << "\n\n";

    out << "[Audio]\n";
    out << "; Default audio input device index\n";
    out << "inputDeviceIndex=" << m_audioInputDeviceIndex << "\n";
    out << "; Audio input device ID (system identifier, hex encoded)\n";
    out << "inputDeviceId=" << QString::fromLatin1(m_audioInputDeviceId.toHex()) << "\n";
    out << "; Audio output device ID (system identifier, hex encoded; empty = default)\n";
    out << "outputDeviceId=" << QString::fromLatin1(m_audioOutputDeviceId.toHex()) << "\n\n";

    out << "[Project]\n";
    out << "; Default project directory for storing recorded audio and MIDI files\n";
    out << "location=" << m_projectLocation << "\n";

    file.close();
}
