#include "appsettings.h"
#include <QSettings>
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QTextStream>
#include <QStringConverter>

static QString configFilePath()
{
    QString dir = QCoreApplication::applicationDirPath();
    return dir + QDir::separator() + "config.ini";
}

AppSettings& AppSettings::instance()
{
    static AppSettings instance;
    return instance;
}

AppSettings::AppSettings()
{
    load();
}

void AppSettings::load()
{
    const QString path = configFilePath();
    QSettings settings(path, QSettings::IniFormat);

    settings.beginGroup("");
    m_theme = settings.value("theme", "dark").toString();
    m_language = settings.value("language").toString();
    m_recordingDebugLog = settings.value("recordingDebugLog", false).toBool();
    m_metronomeEnabled = settings.value("metronomeEnabled", false).toBool();
    m_metronomeBpm = settings.value("metronomeBpm", 120).toInt();
    m_ledColor = settings.value("ledColor", "light_green").toString();
    settings.endGroup();
    m_midiDeviceIndex = settings.value("MIDI/deviceIndex", 0).toInt();
    m_soundFontPath = settings.value("MIDI/soundFontPath").toString();
    m_midiVolumePercent = settings.value("MIDI/volumePercent", 100).toInt();
    m_audioInputDeviceIndex = settings.value("Audio/inputDeviceIndex", 0).toInt();
    QString deviceIdHex = settings.value("Audio/inputDeviceId").toString();
    m_audioInputDeviceId = QByteArray::fromHex(deviceIdHex.toLatin1());
    QString outputDeviceIdHex = settings.value("Audio/outputDeviceId").toString();
    m_audioOutputDeviceId = QByteArray::fromHex(outputDeviceIdHex.toLatin1());
    m_projectLocation = settings.value("Project/location").toString();
}

void AppSettings::save()
{
    const QString path = configFilePath();
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return;

    QTextStream out(&file);
    out.setEncoding(QStringConverter::Utf8);

    out << "; Musician's Canvas Configuration\n";
    out << "; This file is automatically generated. Edit with care.\n\n";

    out << "[General]\n";
    out << "; GUI theme: dark or light\n";
    out << "theme=" << m_theme << "\n";
    out << "; Language (empty = system default)\n";
    out << "language=" << m_language << "\n";
    out << "; Write recording debug information to recording_debug.txt\n";
    out << "recordingDebugLog=" << (m_recordingDebugLog ? "true" : "false") << "\n";
    out << "; Enable metronome tick during recording\n";
    out << "metronomeEnabled=" << (m_metronomeEnabled ? "true" : "false") << "\n";
    out << "; Metronome beats per minute\n";
    out << "metronomeBpm=" << m_metronomeBpm << "\n";
    out << "; LED display color (light_red, dark_red, light_green, dark_green,\n";
    out << ";   light_blue, dark_blue, yellow, orange, light_cyan, dark_cyan)\n";
    out << "ledColor=" << m_ledColor << "\n\n";

    out << "[MIDI]\n";
    out << "; Default MIDI input device index (-1 for no device)\n";
    out << "deviceIndex=" << m_midiDeviceIndex << "\n";
    out << "; Path to SoundFont (.sf2) file for MIDI synthesis\n";
    out << "soundFontPath=" << m_soundFontPath << "\n";
    out << "; MIDI volume for software synth rendering during playback (percent, 0-200)\n";
    out << "volumePercent=" << m_midiVolumePercent << "\n\n";

    out << "[Audio]\n";
    out << "; Default audio input device index\n";
    out << "inputDeviceIndex=" << m_audioInputDeviceIndex << "\n";
    out << "; Audio input device ID (system identifier, hex encoded)\n";
    out << "inputDeviceId=" << QString::fromLatin1(m_audioInputDeviceId.toHex()) << "\n";
    out << "; Audio output device ID (system identifier, hex encoded; empty = default)\n";
    out << "outputDeviceId=" << QString::fromLatin1(m_audioOutputDeviceId.toHex()) << "\n\n";

    out << "[Project]\n";
    out << "; Default project directory for storing recorded audio and MIDI files\n";
    out << "location=" << m_projectLocation << "\n";

    file.close();
}
